In [1]:
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from mastercard import dist_visualisation, dist_categorical_visualisation
from mastercard.config import INTERIM_DATA_DIR

2025-06-09 17:56:52.001 | INFO     | mastercard.config:<module>:11 - PROJ_ROOT path is: /home/lipov/projects/mastercard_sgh

In [2]:
PROCESSED_DATA = Path("../data/processed")
INTERIM_DATA = Path("../data/interim")
FIGURES_PATH = Path('../reports/figures')

In [3]:
df = pd.read_parquet(INTERIM_DATA / 'merge_data.parquet')

In [4]:
df.columns

Index(['transaction_id', 'timestamp', 'user_id', 'merchant_id', 'amount',
       'channel', 'currency', 'device', 'location', 'payment_method',
       'is_international', 'session_length_seconds', 'is_first_time_merchant',
       'is_fraud', 'age', 'sex', 'education', 'primary_source_of_income',
       'sum_of_monthly_installments', 'sum_of_monthly_expenses',
       'country_user', 'signup_date', 'risk_score', 'category',
       'country_merchant', 'trust_score', 'number_of_alerts_last_6_months',
       'avg_transaction_amount', 'account_age_months', 'has_fraud_history'],
      dtype='object')

In [5]:
df.drop(columns=['currency', 'user_id', 'merchant_id', 'location'], inplace=True)

In [6]:
df.columns

Index(['transaction_id', 'timestamp', 'amount', 'channel', 'device',
       'payment_method', 'is_international', 'session_length_seconds',
       'is_first_time_merchant', 'is_fraud', 'age', 'sex', 'education',
       'primary_source_of_income', 'sum_of_monthly_installments',
       'sum_of_monthly_expenses', 'country_user', 'signup_date', 'risk_score',
       'category', 'country_merchant', 'trust_score',
       'number_of_alerts_last_6_months', 'avg_transaction_amount',
       'account_age_months', 'has_fraud_history'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   transaction_id                  500000 non-null  object
 1   timestamp                       500000 non-null  datetime64[ns]
 2   amount                          500000 non-null  float64
 3   channel                         500000 non-null  object
 4   device                          500000 non-null  object
 5   payment_method                  500000 non-null  object
 6   is_international                500000 non-null  int64
 7   session_length_seconds          500000 non-null  int64
 8   is_first_time_merchant          500000 non-null  int64
 9   is_fraud                        500000 non-null  int64
 10  age                             500000 non-null  int64
 11  sex                             500000 non-null  object
 12  education                       403434 non-null  object
 13  primary_source_of_income        500000 non-null  object
 14  sum_of_monthly_installments     500000 non-null  float64
 15  sum_of_monthly_expenses         500000 non-null  float64
 16  country_user                    500000 non-null  object
 17  signup_date                     500000 non-null  datetime64[ns]
 18  risk_score                      500000 non-null  float64
 19  category                        500000 non-null  object
 20  country_merchant                500000 non-null  object
 21  trust_score                     500000 non-null  float64
 22  number_of_alerts_last_6_months  500000 non-null  int64
 23  avg_transaction_amount          500000 non-null  float64
 24  account_age_months              500000 non-null  int64
 25  has_fraud_history               500000 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(8), object(10)
memory usage: 99.2+ MB

In [8]:
df['education'] = df['education'].fillna('Missing')

In [9]:
df.drop(columns=['transaction_id'], inplace=True)

In [10]:
df.columns

Index(['timestamp', 'amount', 'channel', 'device', 'payment_method',
       'is_international', 'session_length_seconds', 'is_first_time_merchant',
       'is_fraud', 'age', 'sex', 'education', 'primary_source_of_income',
       'sum_of_monthly_installments', 'sum_of_monthly_expenses',
       'country_user', 'signup_date', 'risk_score', 'category',
       'country_merchant', 'trust_score', 'number_of_alerts_last_6_months',
       'avg_transaction_amount', 'account_age_months', 'has_fraud_history'],
      dtype='object')

In [11]:
df['education']

0            Bachelor
1                 PhD
2            Bachelor
3              Master
4                 PhD
             ...
499995       Bachelor
499996    High School
499997       Bachelor
499998    High School
499999        Missing
Name: education, Length: 500000, dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   timestamp                       500000 non-null  datetime64[ns]
 1   amount                          500000 non-null  float64
 2   channel                         500000 non-null  object
 3   device                          500000 non-null  object
 4   payment_method                  500000 non-null  object
 5   is_international                500000 non-null  int64
 6   session_length_seconds          500000 non-null  int64
 7   is_first_time_merchant          500000 non-null  int64
 8   is_fraud                        500000 non-null  int64
 9   age                             500000 non-null  int64
 10  sex                             500000 non-null  object
 11  education                       500000 non-null  object
 12  primary_source_of_income        500000 non-null  object
 13  sum_of_monthly_installments     500000 non-null  float64
 14  sum_of_monthly_expenses         500000 non-null  float64
 15  country_user                    500000 non-null  object
 16  signup_date                     500000 non-null  datetime64[ns]
 17  risk_score                      500000 non-null  float64
 18  category                        500000 non-null  object
 19  country_merchant                500000 non-null  object
 20  trust_score                     500000 non-null  float64
 21  number_of_alerts_last_6_months  500000 non-null  int64
 22  avg_transaction_amount          500000 non-null  float64
 23  account_age_months              500000 non-null  int64
 24  has_fraud_history               500000 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(8), object(9)
memory usage: 95.4+ MB

In [13]:
categorical_cols = ['channel', 'device', 'payment_method', 'sex', 'education', 'primary_source_of_income', 'category']

In [14]:
df_encoded = pd.get_dummies(df, columns=categorical_cols, dtype=int, drop_first=True)

In [15]:
df_encoded.shape

(500000, 42)

In [16]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 42 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   timestamp                              500000 non-null  datetime64[ns]
 1   amount                                 500000 non-null  float64
 2   is_international                       500000 non-null  int64
 3   session_length_seconds                 500000 non-null  int64
 4   is_first_time_merchant                 500000 non-null  int64
 5   is_fraud                               500000 non-null  int64
 6   age                                    500000 non-null  int64
 7   sum_of_monthly_installments            500000 non-null  float64
 8   sum_of_monthly_expenses                500000 non-null  float64
 9   country_user                           500000 non-null  object
 10  signup_date                            500000 non-null  datetime64[ns]
 11  risk_score                             500000 non-null  float64
 12  country_merchant                       500000 non-null  object
 13  trust_score                            500000 non-null  float64
 14  number_of_alerts_last_6_months         500000 non-null  int64
 15  avg_transaction_amount                 500000 non-null  float64
 16  account_age_months                     500000 non-null  int64
 17  has_fraud_history                      500000 non-null  int64
 18  channel_mobile                         500000 non-null  int64
 19  channel_online                         500000 non-null  int64
 20  device_Web                             500000 non-null  int64
 21  device_iOS                             500000 non-null  int64
 22  payment_method_credit_card             500000 non-null  int64
 23  payment_method_debit_card              500000 non-null  int64
 24  payment_method_mobile_payment          500000 non-null  int64
 25  sex_Male                               500000 non-null  int64
 26  sex_Other                              500000 non-null  int64
 27  education_High School                  500000 non-null  int64
 28  education_Master                       500000 non-null  int64
 29  education_Missing                      500000 non-null  int64
 30  education_PhD                          500000 non-null  int64
 31  primary_source_of_income_Employment    500000 non-null  int64
 32  primary_source_of_income_Retirement    500000 non-null  int64
 33  primary_source_of_income_Savings       500000 non-null  int64
 34  primary_source_of_income_Student Aid   500000 non-null  int64
 35  primary_source_of_income_Unemployment  500000 non-null  int64
 36  category_education                     500000 non-null  int64
 37  category_electronics                   500000 non-null  int64
 38  category_gaming                        500000 non-null  int64
 39  category_grocery                       500000 non-null  int64
 40  category_restaurants                   500000 non-null  int64
 41  category_travel                        500000 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(32), object(2)
memory usage: 160.2+ MB

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
numerical_cols = ['amount', 'session_length_seconds', 'age', 'sum_of_monthly_expenses', 'risk_score' ,'trust_score', 'number_of_alerts_last_6_months', 'avg_transaction_amount', 'account_age_months']

In [19]:
df_encoded.describe()

,timestamp,amount,is_international,session_length_seconds,is_first_time_merchant,is_fraud,age,sum_of_monthly_installments,sum_of_monthly_expenses,signup_date,...,primary_source_of_income_Retirement,primary_source_of_income_Savings,primary_source_of_income_Student Aid,primary_source_of_income_Unemployment,category_education,category_electronics,category_gaming,category_grocery,category_restaurants,category_travel
count,500000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000,...,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000
mean,2022-12-31 16:45:04.497720576,49.915662,0.928662,614.987182,0.501248,0.084822,45.951568,301.355199,1182.346649,2022-10-06 13:27:43.660799744,...,0.165126,0.164698,0.162216,0.173432,0.140724,0.153108,0.127132,0.156492,0.134314,0.136254
min,2022-01-01 00:06:00,0.000000,0.000000,30.000000,0.000000,0.000000,18.000000,0.010000,0.040000,2020-04-21 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2022-07-01 11:03:45,14.370000,1.000000,323.000000,0.000000,0.000000,32.000000,87.430000,353.660000,2021-07-09 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2022-12-31 20:08:30,34.560000,1.000000,614.000000,1.000000,0.000000,46.000000,207.330000,825.190000,2022-10-08 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2023-07-02 08:45:15,69.172500,1.000000,907.000000,1.000000,0.000000,60.000000,418.000000,1650.440000,2023-12-29 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2023-12-31 23:57:00,714.860000,1.000000,1200.000000,1.000000,1.000000,74.000000,3165.700000,10994.330000,2025-03-22 00:00:00,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,NaN,49.990657,0.257389,338.091496,0.499999,0.278617,16.525405,303.515308,1168.967960,NaN,...,0.371295,0.370908,0.368649,0.378621,0.347737,0.360092,0.333121,0.363322,0.340990,0.343058

In [20]:
scaler = StandardScaler()

In [21]:
df_encoded[numerical_cols]= scaler.fit_transform(df_encoded[numerical_cols])

In [22]:
df_encoded.describe()

,timestamp,amount,is_international,session_length_seconds,is_first_time_merchant,is_fraud,age,sum_of_monthly_installments,sum_of_monthly_expenses,signup_date,...,primary_source_of_income_Retirement,primary_source_of_income_Savings,primary_source_of_income_Student Aid,primary_source_of_income_Unemployment,category_education,category_electronics,category_gaming,category_grocery,category_restaurants,category_travel
count,500000,5.000000e+05,500000.000000,5.000000e+05,500000.000000,500000.000000,5.000000e+05,500000.000000,5.000000e+05,500000,...,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000
mean,2022-12-31 16:45:04.497720576,8.754597e-17,0.928662,1.131397e-16,0.501248,0.084822,-1.078746e-16,301.355199,2.015224e-16,2022-10-06 13:27:43.660799744,...,0.165126,0.164698,0.162216,0.173432,0.140724,0.153108,0.127132,0.156492,0.134314,0.136254
min,2022-01-01 00:06:00,-9.985008e-01,0.000000,-1.730265e+00,0.000000,0.000000,-1.691432e+00,0.010000,-1.011412e+00,2020-04-21 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2022-07-01 11:03:45,-7.110468e-01,1.000000,-8.636345e-01,0.000000,0.000000,-8.442505e-01,87.430000,-7.089052e-01,2021-07-09 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2022-12-31 20:08:30,-3.071710e-01,1.000000,-2.919869e-03,1.000000,0.000000,2.930763e-03,207.330000,-3.055319e-01,2022-10-08 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2023-07-02 08:45:15,3.852091e-01,1.000000,8.637103e-01,1.000000,0.000000,8.501120e-01,418.000000,4.004334e-01,2023-12-29 00:00:00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2023-12-31 23:57:00,1.330139e+01,1.000000,1.730340e+00,1.000000,1.000000,1.697293e+00,3165.700000,8.393723e+00,2025-03-22 00:00:00,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,NaN,1.000001e+00,0.257389,1.000001e+00,0.499999,0.278617,1.000001e+00,303.515308,1.000001e+00,NaN,...,0.371295,0.370908,0.368649,0.378621,0.347737,0.360092,0.333121,0.363322,0.340990,0.343058

In [23]:
df_encoded.to_parquet(INTERIM_DATA / 'df_encoded.parquet')

In [24]:
df_encoded.shape

(500000, 42)